### ISSUE TITLE
App does not compile with latest version of maven

### ISSUE THREAD

**Issue by blefebvre** [blefebvre/aem-phonegap-kitchen-sink#43]

**Comment by blefebvre** [comment]
Version 3.3 not supported.

**Comment by damianleung** [comment]
Updating slf4j might solve this problem. Related problem (and fix) found here: https://github.com/eirslett/frontend-maven-plugin/issues/179#issuecomment-84942696

**Comment by blefebvre** [comment]
Thanks for following up, @damianleung. I managed to work around the issue by updating the version of content-package-maven-plugin we're using.
