### ISSUE TITLE
kitchen-sink-books-update.csv missing from the demo instructions

### ISSUE THREAD

**Issue by torinmb** [blefebvre/aem-phonegap-kitchen-sink#48]
In the [demo](https://github.com/blefebvre/aem-phonegap-kitchen-sink/tree/master/demos) the link to [kitchen-sink-books-update.csv](https://github.com/blefebvre/aem-phonegap-kitchen-sink/blob/master/demos/blob/master/content/src/main/content/jcr_root/etc/commerce/products/kitchen-sink-books-update.csv) is missing.

**Comment by blefebvre** [comment]
Sorry about that! Fixed now. 3rd time a charm.
